### PR TITLE
FEAT: Adding terminal feature

### PR DESCRIPTION
**Pull request by jackstockley89**
Terminal is a command for the cloud-platform cli to enable setup of a users shell to include the right environment variables for awscli, kubectl and terraform to make sure that workspaces and cluster are both the same. 

The script does require a user to have aws config and credentials place in a particular directory. the kubecfg uses the awscli to set context as well as update the config under .kube, if missing it will create the config, dependant on aws credentials

### CODE REVIEW

**Comment by jackstockley89** [comment]
linked ticket
https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/3612

**Comment by jasonBirchall** [comment]
Is this ready for review, or are you still working on it?

**Comment by jasonBirchall** [comment]
Side note: A nice way to standardise your commit messages (using conventional commits) is to use the [commitzen](https://github.com/commitizen/cz-cli) cli tool.

**Comment by jasonBirchall** [comment]
I'm going to close this, but feel free to re-open it when it comes time to revisit it.

**Pull request closed without merging**
